name: update-from-api-and-csv

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install deps
        run: |
          pip install requests
      - name: execute python script to get data from API
        run: |
          python api.py
        working-directory: scripts
      - name: commit changes from API
        run: |
          git config user.email "imran271828@gmail.com"
          git config user.name "Muhammad Imran"
          git add .
          git commit -m 'update data from API'
          git push

  update_geojson:
    needs: getdata
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: execute python script to update GeoJSON
        run: |
          python update_rainfall.py
        working-directory: scripts
      - name: commit changes to GeoJSON
        run: |
          git config user.email "imran271828@gmail.com"
          git config user.name "Muhammad Imran"
          git add .
          git commit -m 'update GeoJSON with rainfall data' || true  # Proceed even if there's nothing to commit
          git pull --rebase  # Rebase local changes on top of remote changes
          git push

  deploy:
    needs: update_geojson
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
